import { Student, Room, Payment, Complaint } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '123-456-7890',
    roomNumber: '101',
    roomId: '1',
    course: 'Computer Science',
    admissionDate: '2023-09-01',
    status: 'Active',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '098-765-4321',
    roomNumber: '102',
    roomId: '2',
    course: 'Information Technology',
    admissionDate: '2023-09-05',
    status: 'Active',
  },
  {
    id: '3',
    name: 'Mike Ross',
    email: 'mike@example.com',
    phone: '555-0123-456',
    roomNumber: '201',
    roomId: '3',
    course: 'Business Admin',
    admissionDate: '2023-10-12',
    status: 'Active',
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: '1',
    number: '101',
    type: 'Double',
    status: 'Available',
    capacity: 2,
    currentOccupants: 1,
    pricePerMonth: 500,
  },
  {
    id: '2',
    number: '102',
    type: 'Single',
    status: 'Full',
    capacity: 1,
    currentOccupants: 1,
    pricePerMonth: 800,
  },
  {
    id: '3',
    number: '201',
    type: 'Double',
    status: 'Available',
    capacity: 2,
    currentOccupants: 1,
    pricePerMonth: 500,
  },
  {
    id: '4',
    number: '202',
    type: 'Triple',
    status: 'Available',
    capacity: 3,
    currentOccupants: 0,
    pricePerMonth: 400,
  },
  {
    id: '5',
    number: '301',
    type: 'Quad',
    status: 'Available',
    capacity: 4,
    currentOccupants: 0,
    pricePerMonth: 300,
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: '1',
    studentId: '1',
    studentName: 'John Doe',
    roomNumber: '101',
    amount: 500,
    date: '2024-03-01',
    month: 'March 2024',
    status: 'Paid',
    method: 'Online',
  },
  {
    id: '2',
    studentId: '2',
    studentName: 'Jane Smith',
    roomNumber: '102',
    amount: 800,
    date: '2024-03-05',
    month: 'March 2024',
    status: 'Paid',
    method: 'Card',
  },
  {
    id: '3',
    studentId: '3',
    studentName: 'Mike Ross',
    roomNumber: '201',
    amount: 500,
    date: '2024-03-10',
    month: 'March 2024',
    status: 'Pending',
    method: 'Cash',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: '1',
    studentId: '1',
    studentName: 'John Doe',
    roomNumber: '101',
    title: 'Leaking Faucet',
    description: 'The bathroom faucet has been leaking since morning.',
    date: '2024-03-15',
    status: 'Pending',
    priority: 'Medium',
  },
  {
    id: '2',
    studentId: '2',
    studentName: 'Jane Smith',
    roomNumber: '102',
    title: 'AC Not Working',
    description: 'The air conditioner is making loud noise and not cooling.',
    date: '2024-03-14',
    status: 'In Progress',
    priority: 'High',
  },
];
